// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuditLogSchema from './schema/audit-log.schema';
import * as AuthSchema from './schema/auth.schema';
import * as EmailLogSchema from './schema/email-log.schema';
import * as EmailTemplateSchema from './schema/email-template.schema';
import * as EnumSchema from './schema/enum.schema';
import * as MediaSchema from './schema/media.schema';
import * as RelationSchema from './schema/relation.schema';
import * as SecurityStoreSchema from './schema/security-store.schema';
import * as SmtpProviderSchema from './schema/smtp-provider.schema';
import * as SystemSchema from './schema/system.schema';

const schema = {
	...AuditLogSchema,
	...AuthSchema,
	...EmailLogSchema,
	...EmailTemplateSchema,
	...EnumSchema,
	...MediaSchema,
	...RelationSchema,
	...SecurityStoreSchema,
	...SmtpProviderSchema,
	...SystemSchema,
};

export default schema;
